# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZWP62epfm989nXn88jHVnME9d-S3kA0
"""

import streamlit as st

while True:
    user_input = st.text_input('Type "yes" or "no":', key='input')
    if user_input.lower() == 'yes':
        st.write('You typed yes!')
        break
    elif user_input.lower() == 'no':
        st.write('You typed no, please try again.')
    else:
        st.write('Please type either "yes" or "no".')