# -*- coding: utf-8 -*-
"""scenario_1_investment_recommendations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIkQHy1UmyQOYE8mg_zABYXfEvHxXxsr
"""

# Investment strategy options
strategies = [
  "100% Debt",
  "40% Equity, 60% Debt",
  "60% Equity, 40% Debt",
  "80% Equity, 20% Debt",
  "100% Equity"
]

etfs = [
'BMO Fixed Income ETF Portfolio\nBMO USD Income ETF Portfolio\nBMO USD Conservative ETF Portfolio\nBMO Income ETF Portfolio\nBMO Conservative ETF Portfolio',
'BMO Balanced ETF Portfolio\nBMO Monthly Dividend Fund Ltd.\nBMO Diversified Income Portfolio\nBMO Monthly Income Fund\nBMO Canadian Income & Growth Fund',
'BMO Growth ETF Portfolio\nBMO Asset Allocation Fund\nBMO Global Monthly Income Fund\nBMO Sustainable Global Balanced Fund\nBMO Concentrated Global Balanced Fund',
'BMO Equity Growth ETF Portfolio\nBMO Global Equity Fund\nBMO Global Low Volatility ETF Class\nBMO Dividend Fund\nBMO Asian Growth and Income Fund',
'BMO Canadian Equity Fund\nBMO Global Equity Fund\nBMO U.S. Equity Growth MFR Fund\nBMO ARK Innovation Fund\nBMO Global Low Volatility ETF Class'
]

# Investment goals
goals = [
  "Retirement",
  "Education fund",
  "Car Fund",
   "Emergency fund",
  "Savings for a Purchase"
]

# Risk profiles
risks = [
  "Low",
  "Medium",
  "High",
   "Very high",
  "Aggressive"
]

# Investment horizons
horizons = [
 "Very Long Term (Over 10 Years)",
 "Long Term (5-10 Years)",
 "Medium Term (1-5 Years)",
 "Short Term (6 Months - 1 Year)",
 "Very Short Term (Under 6 Months)",
]

# Show goal options
print("Investment Goals:")
for num, goal in enumerate(goals, 1):
    print(f"{num}. {goal}")

# Take goal input
goal_num = int(input("Select goal number: "))

# Similarly for risk...
print("Risk Profiles:")
for num, risk in enumerate(risks, 1):
   print(f"{num}. {risk}")

risk_num = int(input("Select risk number: "))

# Similarly for horizon...
print("Investment Horizons:")
for num, horizon in enumerate(horizons, 1):
    print(f"{num}. {horizon}")

horizon_num = int(input("Select horizon number: "))

# Calculating Total Score

total_risk_score = goal_num+risk_num+horizon_num

# Calculating Index - Mapping 3-15 to 0-4

strategy_index = int((total_risk_score/3)-1)

# Recommending a strategy based on the total risk score

recommended_strategy = strategies[strategy_index]

# Printing the strategy to the end user

print(f"Based on your goal of {goals[goal_num-1]}, risk profile of {risks[risk_num-1]} and horizon of {horizons[horizon_num-1]},")
print(f"the recommended investment strategy is: {recommended_strategy}")

see_funds = int(input(f"See list of funds at your own discretion related to {recommended_strategy}? 1 for Yes, 2 for No: "))

if see_funds == 1:
   print("List of funds recommended for you - \n \n"+etfs[strategy_index])
else:
   print("Ok, thanks for using this tool!")

