# -*- coding: utf-8 -*-
"""scenario_3_b_atm_branch_locator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSw6cayyL4wdhxcc8B1uR83SSi3TAJfw
"""

import requests
from IPython.display import display, HTML

# Get location and search type from user
print("Enter 1 for branch or 2 for ATM: ")
search_type = input()

user_location = input("Enter your location: ")

# API key and other params
api_key = 'AIzaSyBwAwx4LVNF9CEFF9u89bgUgAN2TeaAp_g'
radius = 1000

# Geocode location
geocode_url = "https://maps.googleapis.com/maps/api/geocode/json"
params = {'address': user_location, 'key': api_key}
geo_response = requests.get(geocode_url, params=params).json()
location = geo_response['results'][0]['geometry']['location']

# Build search URL
url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

if search_type == "1":
  # bank search parameters
  params = {
    'location': f"{location['lat']},{location['lng']}",
    'radius': radius,
    'type': 'bank',
    'keyword': 'bmo',
    'key': api_key
  }
else:
  # atm search parameters
  params = {
    'location': f"{location['lat']},{location['lng']}",
    'radius': radius,
    'type': 'atm',
    'keyword': 'bmo',
    'key': api_key
  }

# Make request and get results
results = requests.get(url, params=params).json()

# Check for results
if len(results['results']) == 0:
  print("No results found within search radius")
else:
  nearest = results['results'][0]

  # Display name and address
  print(nearest['name'])
  print(nearest['vicinity'])

  # Get lat/lng for map
  lat = nearest['geometry']['location']['lat']
  lng = nearest['geometry']['location']['lng']

  # Construct HTML for Google Maps static image
  map_url = f"https://maps.google.com/maps?q={lat},{lng}&z=16&output=embed"
  map_html = f"""
  <iframe
    width="600"
    height="450"
    frameborder="0" style="border:0"
    src="{map_url}" allowfullscreen>
  </iframe>
  """

  # Display map
  display(HTML(map_html))